### ISSUE TITLE
Color code (§) encoding issues

### ISSUE THREAD

**Issue by Pokechu22** [uyjulian/LiteModWDL#2]
I was doing some testing, and it looks like the chatdebug text is messed up in a09739c.  Rather than properly using a [§ to format the colors](http://minecraftwiki.gamepedia.com/§), it displays a � (both in game and in the files themselves).  The simplest way to fix it would be to just replace all instances of � with the properly escaped version of §, `\u007A` (or in future versions, replacing § with the escaped version).  You probably also could fix the project encoding, which would solve the issue for future versions.

For comparison: 

Coremod version:
![](https://cloud.githubusercontent.com/assets/8334194/8587481/4c318e0e-25b1-11e5-85dc-01e9b4687a7f.png)
Liteloader version:
![](https://cloud.githubusercontent.com/assets/8334194/8587485/571851b8-25b1-11e5-8657-b02a34a53bfc.png)

**Comment by uyjulian** [comment]
I'll fix the source code files to UTF-8. That should fix the problem

**Comment by uyjulian** [comment]
Fixed.
